### ISSUE TITLE
Object learning does not service preempt in LEARN_MODEL state

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_3d_mapping#104]
```
^[[INFO] [WallTime: 1462437864.835321] Preempt on state machine requested!                                                                                                                                     │·····
[ERROR] [WallTime: 1462437864.836312] Failed to preempt contained state 'LEARN_MODEL': Traceback (most recent call last):                                                                                      │·····
  File "/opt/ros/indigo/lib/python2.7/dist-packages/smach/state_machine.py", line 396, in _preempt_current_state                                                                                               │·····
    self._preempted_state.request_preempt()                                                                                                                                                                    │·····
  File "/opt/ros/indigo/lib/python2.7/dist-packages/smach/state_machine.py", line 375, in request_preempt                                                                                                      │·····
    with self._state_transitioning_lock:                                                                                                                                                                       │·····
AttributeError: 'LearnObjectModel' object has no attribute '_state_transitioning_lock'    
```

**Comment by RaresAmbrus** [comment]
@hawesie as far as I know, the metric mapping action server is preemptable, but I'm not sure about the others. I think the whole action is "cancelable", but maybe not preemptable. If you think it could be an issue I can take a look.
